venv-portfolio/portfolio/common/urls.py
from django.urls import path
from . import views


app_name = 'common'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('about/', views.AboutView.as_view(), name='about'),
    path('works/', views.WorksView.as_view(), name='works'),
]

venv-portfolio/portfolio/portfolio/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('common.urls')),
    path('about/', include('common.urls')),
    path('works/', include('common.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

venv-portfolio/portfolio/common/models.py
from email.mime import image
from django.db import models

class Image(models.Model):
    name = models.CharField(max_length=255, unique=True)
    image = models.ImageField(upload_to='images/')

    def __str__(self):
        return self.name

venv-portfolio/portfolio/common/views.py
from django.views import generic

class IndexView(generic.TemplateView):
    template_name = "index.html"

class AboutView(generic.TemplateView):
    template_name = "about.html"

class WorksView(generic.TemplateView):
    template_name = "works.html"

venv-portfolio/portfolio/common/templates/about.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Portfolio | トップページ</title>
{% endblock %}

{% block contents %}
<h3>Hello World</h3>
{% endblock %}

venv-portfolio/portfolio/common/templates/base.html
{% load static %}

<html lang="ja">
    <head>
        <meta charset="UTF-8">
        <meta name="viewport" content="width=deivice-width, initial-scale=1.0">
        <meta name="description" content="">
        <meta name="author" content="">

        <title>{% block title %}{% endblock %}</title>

        <!-- ブートストラップCSS -->
        <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous"> -->
        
        <!-- My style CSS -->
        <link rel="stylesheet" type="text/css" href="{% static 'css/mystyle.css' %}">
        {% block head %}{% endblock %}
    
    </head>
    <body>
        <div class="contena">
            <div class="column-l">
                <header>
                    <h1>TYRN Portfolio</h1>
                    <h2>これまでに作成した作品を掲載しています</h2>
                    <!-- Navigation -->
                    <nav>
                        <ul>
                            <li><a href="{% url 'common:about' %}">ABOUT</a></li>
                            <li><a href="{% url 'common:works' %}">WORKS</a></li>        
                        </ul>
                    </nav>    
                </header> 
            </div>
            <div class="column-r">
                <main>
                    {% block contents %}{% endblock %}
                </main>
            </div>
        </div>
        <footer>
            <p>Copyright &copy;TYRN Portfolio 2022</p>
        </footer>
        <!-- Footer -->
    </body>
    <script src="https://code.jquery.com/jquery-3.4.1.min.js" integrity="sha256-CSXorXvZcTkaix6Yvo6HppcZGetbYMGWSFlBw8HfCJo=" crossorigin="anonymous"></script>
    <script type="text/javascript" src="{% static 'js/leftfixed.js' %}"></script>
</html>

venv-portfolio/portfolio/common/templates/index.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Portfolio | トップページ</title>
{% endblock %}

{% block contents %}
<h3>グラフィックデザイン、Webサイトデザイン<br>できます</h3>
<p>お客様のご希望に併せてデザインいたします</p>
<h4>WorkTime</h4>
<p>本業との両立のため、基本的に作業時間は、２１時以降からです</p>
<img>
<h4>Meeting</h4>
<p>平日は本業があるため、基本的に、土曜、日曜の対応となります<br>２１時以降であれば、平日でも可能です<br>会議システムはZoom、チャットツールはchatworkが使用できます</p>
<img>
<h4>WorkScale</h4>
<p>グラフィックデザインなら、パンフレット、バナーデザイン　など<br>Webデザインなら、LP、企業サイト　など対応可能です</p>
<img>
<h4>Tool、Script</h4>
<p>使用可能デザインツール<br>・illustrator　・photoshop<br>言語<br>・HTML　・CSS　・Javascript<br>・Python（勉強中）<br>・Django（勉強中）</p>
<img>
{% endblock %}

venv-portfolio/portfolio/common/templates/works.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
<title>Portfolio | トップページ</title>
{% endblock %}

{% block contents %}
<h3>Hello World</h3>
{% endblock %}